### ISSUE TITLE
Thesis

### ISSUE THREAD

**Issue by AlexavierCarlen** [w-disaster/svm-ddos-sdn#2]
Hello, do you have the english version of your thesis? I did translate yours using google translate but not sure if it's all correct.

**Comment by w-disaster** [comment]
I'm sorry, there's only an italian version of it :( but if you have doubts feel free to write me an email at: luca.fabri@studio.unibo.it

**Comment by w-disaster** [comment]
> Hello, do you have the english version of your thesis? I did translate yours using google translate but not sure if it's all correct.

I'm sorry, there's only an italian version of it :( but if you have doubts feel free to write me an email at: [luca.fabri@studio.unibo.it](mailto:luca.fabri@studio.unibo.it)
